// KNOWN MISSPELLINGS:
// [K1 - K3]
// L > Q (IQLUSION)
// O > U (UNDERGRUUND)
// E > A (DESPARATLY)
// E > _ (DESPARATLY)
// [Other]
// I > E (DIGETALINTERPRETATU)

export const wordsOfInterest = [
  'KRYPTOS',
  'PALIMPSEST',
  'ABSCISSA',
  'PALIMPSESTABSCISSA',
  'PALIMPSESTABSCISSAKRYPTOS',
  'LUCIDMEMORY',
  'TISYOURPOSITION',
  'SHADOWFORCES',
  'VIRTUALLYINVISIBLE',
  'DIGETALINTERPRETATU',
  'RQ',
  'YR',
  'JIMSANBORN',
  'JAMESSANBORN',
  'HERBERTJAMESSANBORN',
  'HERBERTJAMESSANBORNJR',
  'WILLIAMWEBSTER',
  'WILLIAMHEDGCOCKWEBSTER',
  'EDSCHEIDT',
  'EDWARDSCHEIDT',
];